CREATE DATABASE TASKMANAGEMENT;

INSERT INTO PROJECT VALUES(NULL,'iPhone app UI');
INSERT INTO PROJECT VALUES(NULL,'Android app UI');
INSERT INTO PROJECT VALUES(NULL,'Windows app UI');

INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1033848','MALLIKARJUNA G',NULL,NULL,1);
INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1007379','NEETU T',NULL,NULL,2);
INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1033624','NIKHIL METHARI',NULL,NULL,3);

INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1021774','MONIMA GOGOI',NULL,NULL,1);
INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1033511','KRISHNA SURE',NULL,NULL,2);
INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1036367','TIRUPATHI V N R P',NULL,NULL,3);

INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1033786','KARTHEEK',NULL,NULL,1);
INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1022564','ADITYA',NULL,NULL,2);
INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1223246','SATHYA',NULL,NULL,3);

INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1033210','MOHAN',NULL,NULL,1);
INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1034985','JYOTI R',NULL,NULL,2);
INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1034589','NAGENDRA',NULL,NULL,3);

INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1033343','BHARATH',NULL,NULL,1);
INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1035453','SUMITH',NULL,NULL,2);
INSERT INTO EMPLOYEE VALUES(NULL,NULL,'M1030979','PAVAN',NULL,NULL,3);